name: base
channels:
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.4.4=py311hfc0e8ea_100
  - archspec=0.2.3=pyhd3eb1b0_0
  - boltons=23.0.0=py311h06a4308_0
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py311h06a4308_0
  - cffi=1.16.0=py311h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=24.3.0=py311h06a4308_0
  - conda-content-trust=0.2.0=py311h06a4308_0
  - conda-libmamba-solver=24.1.0=pyhd3eb1b0_0
  - conda-package-handling=2.2.0=py311h06a4308_0
  - conda-package-streaming=0.9.0=py311h06a4308_0
  - cryptography=42.0.5=py311hdda0065_0
  - distro=1.8.0=py311h06a4308_0
  - fmt=9.1.0=hdb19cb5_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py311h06a4308_0
  - jsonpatch=1.33=py311h06a4308_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.6.2=h6ac8c49_2
  - libcurl=8.5.0=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=1.5.8=hfe524e5_1
  - libmambapy=1.5.8=py311h2dafd23_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libsolv=0.7.24=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.10.4=hf1b16e4_1
  - lz4-c=1.9.4=h6a678d5_0
  - menuinst=2.0.2=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=23.2=py311h06a4308_0
  - pcre2=10.42=hebb0a14_0
  - pip=23.3.1=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - pluggy=1.0.0=py311h06a4308_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py311h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.8=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.31.0=py311h06a4308_1
  - ruamel.yaml=0.17.21=py311h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tqdm=4.65.0=py311h92b7b1e_0
  - truststore=0.8.0=py311h06a4308_0
  - urllib3=2.1.0=py311h06a4308_1
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml-cpp=0.8.0=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py311h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.30.1
      - addict==2.4.0
      - aenum==3.1.15
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - albumentations==1.4.7
      - aliyun-python-sdk-core==2.15.1
      - aliyun-python-sdk-kms==2.16.3
      - altair==5.3.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arxiv==2.1.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrdict==2.0.1
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.1
      - bleach==6.1.0
      - blendmodes==2024.1.1
      - blinker==1.8.2
      - blobfile==2.1.1
      - braceexpand==0.1.7
      - cachetools==5.3.3
      - clean-fid==0.1.35
      - click==8.1.7
      - clip==1.0
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.2.1
      - cpm-kernels==1.0.11
      - crcmod==1.7
      - cycler==0.12.1
      - dataclasses-json==0.6.6
      - datasets==2.18.0
      - debugpy==1.8.1
      - decorator==5.1.1
      - deepspeed==0.14.2
      - defusedxml==0.7.1
      - dill==0.3.8
      - diskcache==5.6.3
      - dnspython==2.6.1
      - einops==0.8.0
      - email-validator==2.1.1
      - executing==2.0.1
      - facexlib==0.3.0
      - fairscale==0.4.13
      - fastapi==0.111.0
      - fastapi-cli==0.0.3
      - fastjsonschema==2.19.1
      - feedparser==6.0.10
      - ffmpy==0.3.2
      - filelock==3.14.0
      - filterpy==1.4.5
      - fire==0.6.0
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - ftfy==6.2.0
      - future==1.0.0
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.31.3
      - gradio-client==0.16.3
      - greenlet==3.0.3
      - grpcio==1.63.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.30.2
      - imageio==2.34.1
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - inflection==0.5.1
      - invisible-watermark==0.2.0
      - ipykernel==6.29.4
      - ipython==8.24.0
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==0.10.0
      - joblib==1.4.2
      - json5==0.9.25
      - jsonmerge==1.9.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.0
      - jupyterlab-language-pack-zh-cn==4.2.post0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - kiwisolver==1.4.5
      - kornia==0.7.2
      - kornia-rs==0.1.3
      - langchain==0.1.20
      - langchain-community==0.0.38
      - langchain-core==0.1.52
      - langchain-text-splitters==0.0.2
      - langchainhub==0.1.15
      - langsmith==0.1.59
      - lark==1.1.9
      - latex2mathml==3.77.0
      - lazy-loader==0.4
      - lightning-utilities==0.11.2
      - llvmlite==0.42.0
      - loguru==0.7.2
      - lxml==4.9.4
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.2
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdtex2html==1.3.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - modelscope==1.14.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.1
      - notebook-shim==0.2.4
      - numba==0.59.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open-clip-torch==2.7.0
      - openai==1.30.1
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - orjson==3.10.3
      - oss2==2.18.5
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pebble==5.0.7
      - peft==0.14.0
      - pexpect==4.9.0
      - piexif==1.1.3
      - pillow==10.3.0
      - pillow-avif-plugin==1.4.3
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==3.20.0
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pudb==2024.1
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pycryptodome==3.20.0
      - pycryptodomex==3.20.0
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydeck==0.9.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - pytorch-lightning==2.2.4
      - pytz==2024.1
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - regex==2024.5.15
      - resize-right==0.0.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - ruff==0.4.4
      - safetensors==0.4.3
      - scikit-image==0.23.2
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==2.7.0
      - sentencepiece==0.2.0
      - sgmllib3k==1.0.0
      - shellingham==1.5.4
      - simplejson==3.19.2
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - sqlalchemy==2.0.30
      - sse-starlette==2.1.0
      - stack-data==0.6.3
      - starlette==0.37.2
      - streamlit==1.34.0
      - streamlit-drawable-canvas==0.9.3
      - sympy==1.12
      - tenacity==8.3.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - test-tube==0.7.5
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2024.5.10
      - tiktoken==0.7.0
      - timeout-decorator==0.5.0
      - timm==1.0.3
      - tinycss2==1.3.0
      - tokenizers==0.21.1
      - tomesd==0.1.3
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchdiffeq==0.2.3
      - torchmetrics==1.4.0.post0
      - torchsde==0.2.6
      - torchvision==0.16.2
      - tornado==6.4
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.51.0
      - transformers-stream-generator==0.0.5
      - triton==2.1.0
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - types-requests==2.31.0.20240406
      - typing-extensions==4.11.0
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - ujson==5.10.0
      - ultralytics==8.2.16
      - uri-template==1.3.0
      - urwid==2.6.12
      - urwid-readline==0.14
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - watchdog==4.0.0
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webdataset==0.2.86
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.0.3
      - xformers==0.0.23.post1
      - xxhash==3.4.1
      - yapf==0.40.2
      - yarl==1.9.4
      - zhipuai==2.0.1.20240429
      - zipp==3.18.1
prefix: /root/miniconda3
